### ISSUE TITLE
hi bro, I run it successfully, but he doesn't do anything in the game, do you know what's going on? A model I trained myself.

### ISSUE THREAD

**Issue by yoloaim** [SMEDjs/ow-vision#1]
hi bro, I run it successfully, but he doesn't do anything in the game, do you know what's going on? A model I trained myself.  136001#0354  Can you tell me at your convenience? Thank you,

**Comment by SMEDjs** [comment]
Hey, do you mean the triggerbot, did you toggle it? it has a keybind for it and it should have a green square in the corner of the GUI (instead of red), let me know

**Comment by yoloaim** [comment]
Yes! I activated it! He turned green! Can also identify the target! But he didn't...triggerbot, game I play!Cross Fire,Thank you for your answer! brother

**Comment by yoloaim** [comment]
https://i.imgtg.com/2023/05/21/OOJQMC.png

**Comment by SMEDjs** [comment]
I see. Well, since you are using another model, maybe it doesn't detect heads? By default, it clicks only on the head. You could try changing the `settings` -> `detect` in Detection.py to "detect": [0, 1], and you can try printing something to see if the if statement works on line 77; if it works, it probably comes from `pyautogui` , goodluck and let me know

**Comment by yoloaim** [comment]
I have modified it. But still, no, thanks for your answer.  https://i.imgtg.com/2023/05/21/OOH6OI.png

**Comment by yoloaim** [comment]
model.conf = 0.45   I modified it to this as well.

**Comment by yoloaim** [comment]
https://i.imgtg.com/2023/05/21/OOHXEF.png  I don't know where I am going wrong.It can run normally, but it will not trigger the BOT

**Comment by SMEDjs** [comment]
Add a print("something") above pyautogui.click() around line 78 see if it triggers the click

**Comment by yoloaim** [comment]
ＯＫ　ＢＲＯ

**Comment by yoloaim** [comment]
still the same result

**Comment by krytoi945** [comment]
I launched it, it works, but I didn’t train it, probably that’s why it works slowly, explain how to train it?

**Comment by TristDev49** [comment]
> 

You use yolov8?

**Comment by TristDev49** [comment]
does this still work for current version of overwatch?

**Comment by SMEDjs** [comment]
yes this uses YOLOv8 and it works for any version of overwatch , it just watch the screen

**Comment by Midgxt78** [comment]
But SMEDjs, If I don't use YOLOv8, can triggerbot it still work?
